version: '3.8'

services:
  recommending-client:
    image: silvajorge/recommending-client:latest
    container_name: recommending-client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_RECOMMENDATION_API_URL=http://localhost:30001/api/recommend
      - REACT_APP_SONGS_PATH=https://raw.githubusercontent.com/jorgesilva2407/recommending-system/main/data/playlists.csv
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS="--max-old-space-size=4096"
