apiVersion: v1
kind: Service
metadata:
  name: recommending-client
  namespace: jorgesilva
spec:
  selector:
    app: recommending-client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002
  type: NodePort
