apiVersion: batch/v1
kind: Job
metadata:
  name: recommending-model-job
  namespace: jorgesilva
spec:
  template:
    spec:
      containers:
        - name: recommending-model-job
          image: silvajorge/recommending-model:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /mnt/data
              name: data-volume
          env:
            - name: INPUT_FILENAME
              value: /mnt/data/playlists.csv
            - name: OUTPUT_FILENAME
              value: /mnt/data/model.pkl
            - name: MIN_SUPPORT
              value: "0.1"
            - name: MIN_CONFIDENCE
              value: "0.5"
      restartPolicy: Never
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: project2-pvc-jorgesilva
