apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jorgesilva
  name: project2-pv2-jorgesilva
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: default-storage-class
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/jlsilva/workspace/cloud/tp2/recommending-system/data
