apiVersion: v1
kind: Service
metadata:
  name: recommending-api
spec:
  selector:
    app: recommending-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
  type: NodePort
