name: Build and Deploy Client

on:
  push:
    branches:
      - main
    paths:
      - client/**
      - .github/workflows/build-and-deploy-client.yml

jobs:
  build-and-push:
    name: Build and Push Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Client image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/recommending-client:latest -f client/Dockerfile ./client
          docker push ${{ secrets.DOCKERHUB_USER }}/recommending-client:latest

    outputs:
      commit_hash: ${{ steps.vars.outputs.commit_hash }}
