name: Build and Deploy Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set commit hash
        id: vars
        run: echo "commit_hash=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and Push API image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/recommending-api:${{ env.commit_hash }} -f api/Dockerfile ./api
          docker push ${{ secrets.DOCKERHUB_USER }}/recommending-api:${{ env.commit_hash }}

      - name: Build and Push Client image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/recommending-client:${{ env.commit_hash }} -f client/Dockerfile ./client
          docker push ${{ secrets.DOCKERHUB_USER }}/recommending-client:${{ env.commit_hash }}

      - name: Build and Push Model image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/recommending-model:${{ env.commit_hash }} -f model/Dockerfile ./model
          docker push ${{ secrets.DOCKERHUB_USER }}/recommending-model:${{ env.commit_hash }}

  update-kubernetes-repo:
    name: Update Kubernetes Deployment Files
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kubernetes Repository
        uses: actions/checkout@v3
        with:
          repository: "jorgesilva2407/kubernetes-recommending-system"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: kubernetes

      - name: Update API Deployment
        run: |
          cd kubernetes/api
          sed -i "s|image: ${{ secrets.DOCKERHUB_USER }}/recommending-api:.*|image: ${{ secrets.DOCKERHUB_USER }}/recommending-api:${{ env.commit_hash }}|" deployment.yml

      - name: Update Client Deployment
        run: |
          cd kubernetes/client
          sed -i "s|image: ${{ secrets.DOCKERHUB_USER }}/recommending-client:.*|image: ${{ secrets.DOCKERHUB_USER }}/recommending-client:${{ env.commit_hash }}|" deployment.yml

      - name: Update Model Deployment
        run: |
          cd kubernetes/model
          sed -i "s|image: ${{ secrets.DOCKERHUB_USER }}/recommending-model:.*|image: ${{ secrets.DOCKERHUB_USER }}/recommending-model:${{ env.commit_hash }}|" job.yml

      - name: Commit and Push Changes
        run: |
          cd kubernetes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update images to ${{ env.commit_hash }}"
          git push origin main
